name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: List repository files
        run: |
          pwd
          ls -la
          find . -name "*.sln*" -o -name "*.csproj"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore AirlineBookingSystem/AirlineBookingSystem.slnx

      - name: Build solution
        run: dotnet build AirlineBookingSystem/AirlineBookingSystem.slnx --configuration Release --no-restore

      - name: Run tests
        run: dotnet test AirlineBookingSystem/AirlineBookingSystem.slnx --configuration Release --no-build